ContactApp/mysite/contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'


urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('person/<int:pk>', views.contact_detail, name='contact_detail'),
    path('person/new', views.contact_new, name='contact_new'),
    path('person/<int:pk>/edit', views.contact_edit, name='contact_edit'),
    path('person/<int:pk>/delete', views.contact_delete, name='contact_delete'),
]

ContactApp/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls', namespace='contact'))
]

ContactApp/mysite/contact/models.py
from django.db import models
from django.utils import timezone


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=50)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)
    
    def __str__(self):
        return self.full_name()

ContactApp/mysite/contact/forms.py
from django import forms
from .models import Person



class PersonForm(forms.ModelForm):
    class Meta:
            model = Person
            fields = ('first_name', 'last_name', 'email', 'phone')

ContactApp/mysite/contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Person
from .forms import PersonForm



def contact_list(request):
    persons = Person.objects.all().order_by('first_name')
    return render(request, 'contact/contact_list.html', {'persons': persons})

def contact_detail(request, pk):
    person = get_object_or_404(Person, pk=pk)
    return render(request, 'contact/contact_detail.html', {'person': person})

def contact_new(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = PersonForm()
    return render(request, 'contact/contact_edit.html', {'form': form})


def contact_edit(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('/person/' + str(person.pk))
    else:
        form = PersonForm(instance=person)
    return render(request, 'contact/contact_edit.html', {'form': form})


def contact_delete(request, pk):
    person = get_object_or_404(Person, pk=pk)
    
    person.delete()
    return redirect('/')










ContactApp/mysite/contact/templates/contact/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Książka Telefoniczna</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'contact:contact_new' %}" class="float-right"><i class="far fa-plus-square"></i></a>
            <h1><a href="/">Książka Telefoniczna</a></h1>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

ContactApp/mysite/contact/templates/contact/contact_detail.html
{% extends 'contact/base.html' %}
{% block content %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ person.full_name }}</h5>
        <p class="card-text">Email- <a href="mailto:{{ person.email }}">{{ person.email }}</a></p>
        <p class="card-text">Telefon- <a href="tel:{{ person.phone }}">{{ person.phone }}</a></p>
        <a href="{% url 'contact:contact_edit' person.id %}"><button class="btn btn-primary">Edytuj</button></a>
        <a href="{% url 'contact:contact_delete' person.id %}"><button class="btn btn-primary">Usuń</button></a>
      </div>
    </div>
{% endblock %}

ContactApp/mysite/contact/templates/contact/contact_edit.html
{% extends 'contact/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    {{ form.as_p }}
    </div>
    <input class="btn btn-primary" type="submit" value="Save" />
</form>
{% endblock %}

ContactApp/mysite/contact/templates/contact/contact_list.html
{% extends 'contact/base.html' %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            {% for person in persons %}
                <div>
                    <li class="list-group-item"><a href="{% url 'contact:contact_detail' person.id %}">{{ person.full_name }}</a></li>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}